# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 80))
        self.navbar.setStyleSheet("background-color: rgb(10, 49, 108);")
        self.navbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = QtWidgets.QFrame(self.navbar)
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.logo_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.logo_frame)
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_2.addWidget(self.logo_label)
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.navbar)
        self.title_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Arial\";")
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_3.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.navbar_buttons = QtWidgets.QFrame(self.navbar)
        self.navbar_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar_buttons.setObjectName("navbar_buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar_buttons)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.OP1 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP1.setObjectName("OP1")
        self.horizontalLayout_4.addWidget(self.OP1)
        self.OP2 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP2.setObjectName("OP2")
        self.horizontalLayout_4.addWidget(self.OP2)
        self.OP3 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP3.setObjectName("OP3")
        self.horizontalLayout_4.addWidget(self.OP3)
        self.OP4 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP4.setObjectName("OP4")
        self.horizontalLayout_4.addWidget(self.OP4)
        self.horizontalLayout.addWidget(self.navbar_buttons)
        self.verticalLayout.addWidget(self.navbar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "ISPE TOOL"))
        self.OP1.setText(_translate("MainWindow", "PushButton"))
        self.OP2.setText(_translate("MainWindow", "PushButton"))
        self.OP3.setText(_translate("MainWindow", "PushButton"))
        self.OP4.setText(_translate("MainWindow", "PushButton"))
