# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 80))
        self.navbar.setStyleSheet("\n"
"background-color: rgb(20, 55, 90);\n"
"")
        self.navbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = QtWidgets.QFrame(self.navbar)
        self.logo_frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.logo_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.logo_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.logo_frame)
        self.logo_label.setMaximumSize(QtCore.QSize(125, 100))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/images/txdot-logo-new.svg"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_2.addWidget(self.logo_label)
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.navbar)
        self.title_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.title_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Arial\";")
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_3.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.line = QtWidgets.QFrame(self.navbar)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.navbar_buttons = QtWidgets.QFrame(self.navbar)
        self.navbar_buttons.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial\";")
        self.navbar_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navbar_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar_buttons.setObjectName("navbar_buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar_buttons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.OP1 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP1.setFlat(True)
        self.OP1.setObjectName("OP1")
        self.horizontalLayout_4.addWidget(self.OP1)
        self.OP2 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP2.setFlat(True)
        self.OP2.setObjectName("OP2")
        self.horizontalLayout_4.addWidget(self.OP2)
        self.OP3 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP3.setFlat(True)
        self.OP3.setObjectName("OP3")
        self.horizontalLayout_4.addWidget(self.OP3)
        self.OP4 = QtWidgets.QPushButton(self.navbar_buttons)
        self.OP4.setAutoDefault(False)
        self.OP4.setDefault(False)
        self.OP4.setFlat(True)
        self.OP4.setObjectName("OP4")
        self.horizontalLayout_4.addWidget(self.OP4)
        self.horizontalLayout.addWidget(self.navbar_buttons)
        self.verticalLayout.addWidget(self.navbar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ispe_page = QtWidgets.QWidget()
        self.ispe_page.setObjectName("ispe_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ispe_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ispe_page_sub_op_navbar = QtWidgets.QFrame(self.ispe_page)
        self.ispe_page_sub_op_navbar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ispe_page_sub_op_navbar.setStyleSheet("background-color: rgb(22, 63, 104);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.ispe_page_sub_op_navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ispe_page_sub_op_navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ispe_page_sub_op_navbar.setObjectName("ispe_page_sub_op_navbar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ispe_page_sub_op_navbar)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.ispe_page_sub_op_navbar)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.ispe_page_sub_op_navbar)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.ispe_page_sub_op_navbar)
        self.ispe_page_content = QtWidgets.QFrame(self.ispe_page)
        self.ispe_page_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ispe_page_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ispe_page_content.setObjectName("ispe_page_content")
        self.label = QtWidgets.QLabel(self.ispe_page_content)
        self.label.setGeometry(QtCore.QRect(310, 200, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.ispe_page_content)
        self.stackedWidget.addWidget(self.ispe_page)
        self.viewDb_page = QtWidgets.QWidget()
        self.viewDb_page.setObjectName("viewDb_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.viewDb_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.viewDb_page_op_navbar = QtWidgets.QFrame(self.viewDb_page)
        self.viewDb_page_op_navbar.setMinimumSize(QtCore.QSize(0, 40))
        self.viewDb_page_op_navbar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.viewDb_page_op_navbar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(22, 63, 104);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.viewDb_page_op_navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewDb_page_op_navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewDb_page_op_navbar.setObjectName("viewDb_page_op_navbar")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.viewDb_page_op_navbar)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.viewDb_page_op_navbar)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.viewDb_page_op_navbar)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_8.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.viewDb_page_op_navbar)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.verticalLayout_2.addWidget(self.viewDb_page_op_navbar)
        self.viewDb_page_content = QtWidgets.QFrame(self.viewDb_page)
        self.viewDb_page_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewDb_page_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewDb_page_content.setObjectName("viewDb_page_content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.viewDb_page_content)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_frame = QtWidgets.QFrame(self.viewDb_page_content)
        self.btn_frame.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.btn_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.changeDb_btn = QtWidgets.QPushButton(self.btn_frame)
        self.changeDb_btn.setObjectName("changeDb_btn")
        self.verticalLayout_5.addWidget(self.changeDb_btn)
        self.download_btn = QtWidgets.QPushButton(self.btn_frame)
        self.download_btn.setObjectName("download_btn")
        self.verticalLayout_5.addWidget(self.download_btn)
        self.horizontalLayout_5.addWidget(self.btn_frame)
        self.table_frame = QtWidgets.QFrame(self.viewDb_page_content)
        self.table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_frame.setObjectName("table_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.table_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.table_frame)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_5.addWidget(self.table_frame)
        self.verticalLayout_2.addWidget(self.viewDb_page_content)
        self.stackedWidget.addWidget(self.viewDb_page)
        self.dbOP_page = QtWidgets.QWidget()
        self.dbOP_page.setObjectName("dbOP_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dbOP_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dbOP_page_sub_op_navbar_2 = QtWidgets.QFrame(self.dbOP_page)
        self.dbOP_page_sub_op_navbar_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.dbOP_page_sub_op_navbar_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(22, 63, 104);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.dbOP_page_sub_op_navbar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dbOP_page_sub_op_navbar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dbOP_page_sub_op_navbar_2.setObjectName("dbOP_page_sub_op_navbar_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dbOP_page_sub_op_navbar_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.dbOP_page_sub_op_navbar_2)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.dbOP_page_sub_op_navbar_2)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.verticalLayout_6.addWidget(self.dbOP_page_sub_op_navbar_2)
        self.dbOP_content = QtWidgets.QFrame(self.dbOP_page)
        self.dbOP_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dbOP_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dbOP_content.setObjectName("dbOP_content")
        self.label_2 = QtWidgets.QLabel(self.dbOP_content)
        self.label_2.setGeometry(QtCore.QRect(380, 200, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.dbOP_content)
        self.stackedWidget.addWidget(self.dbOP_page)
        self.analytics_page = QtWidgets.QWidget()
        self.analytics_page.setObjectName("analytics_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.analytics_page)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.dbOP_page_sub_op_navbar_3 = QtWidgets.QFrame(self.analytics_page)
        self.dbOP_page_sub_op_navbar_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.dbOP_page_sub_op_navbar_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(22, 63, 104);")
        self.dbOP_page_sub_op_navbar_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dbOP_page_sub_op_navbar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dbOP_page_sub_op_navbar_3.setObjectName("dbOP_page_sub_op_navbar_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.dbOP_page_sub_op_navbar_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.dbOP_page_sub_op_navbar_3)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_9.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.dbOP_page_sub_op_navbar_3)
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_9.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.dbOP_page_sub_op_navbar_3)
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_9.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.dbOP_page_sub_op_navbar_3)
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_9.addWidget(self.pushButton_11)
        self.verticalLayout_12.addWidget(self.dbOP_page_sub_op_navbar_3)
        self.dbOP_content_2 = QtWidgets.QFrame(self.analytics_page)
        self.dbOP_content_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dbOP_content_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dbOP_content_2.setObjectName("dbOP_content_2")
        self.label_5 = QtWidgets.QLabel(self.dbOP_content_2)
        self.label_5.setGeometry(QtCore.QRect(380, 200, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.dbOP_content_2)
        self.stackedWidget.addWidget(self.analytics_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "ISPE TOOL"))
        self.OP1.setText(_translate("MainWindow", "In Service Performance Evaluation"))
        self.OP2.setText(_translate("MainWindow", "View Database"))
        self.OP3.setText(_translate("MainWindow", "Database Operations"))
        self.OP4.setText(_translate("MainWindow", "Analytics"))
        self.pushButton.setText(_translate("MainWindow", "OP 1"))
        self.pushButton_2.setText(_translate("MainWindow", "OP 2"))
        self.label.setText(_translate("MainWindow", "ISPE PAGE"))
        self.pushButton_5.setText(_translate("MainWindow", "OP 1"))
        self.pushButton_6.setText(_translate("MainWindow", "OP 2"))
        self.pushButton_7.setText(_translate("MainWindow", "OP 3"))
        self.changeDb_btn.setText(_translate("MainWindow", "Change Database"))
        self.download_btn.setText(_translate("MainWindow", "Download"))
        self.pushButton_3.setText(_translate("MainWindow", "OP 1"))
        self.pushButton_4.setText(_translate("MainWindow", "OP 2"))
        self.label_2.setText(_translate("MainWindow", "Database OPS"))
        self.pushButton_8.setText(_translate("MainWindow", "OP 1"))
        self.pushButton_9.setText(_translate("MainWindow", "OP 2"))
        self.pushButton_10.setText(_translate("MainWindow", "OP 3"))
        self.pushButton_11.setText(_translate("MainWindow", "OP 4"))
        self.label_5.setText(_translate("MainWindow", "Analytics"))
import assets.resFile_rc
